### PR TITLE
Hide grid view cover if cover_url not defined (#2347)

### PR DESCRIPTION
**Pull request by goamaral**
# Description
At the moment the grid view cover handles two scenarios
- If cover_url is present, that url is used to display the cover image
- If not, a fallback image is used
We want to extend the second case distinguishing a not defined cover_url from a falsy value.

I noticed that the grid view cover empty state component was really similar to the code at link_to_cover.
So I took the initiative to merge them (the link_to_cover return did not have a wrapping div but I think this is fine 
because adding it does not affect anything visually).

Updated the avo docs to document how add custom styling to the cover. (https://github.com/avo-hq/avodocs/pull/165)

Fixes [# 2347](https://github.com/avo-hq/avo/issues/2347)

# Checklist:
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [X] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording
image
image

## Manual review steps
1. Open Posts in grid view
2. Check if posts with image, show the image
3. Check if posts without image, show the fallback image (avocado)
4. Open Fish in grid view
5. Check if all posts have no cover

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by goamaral** [comment]
There is still a problem to solve. Since my solution was to not render the cover if the :cover_url was not defined, we lost the ability to select the item.

Other solution would be to early return render_cover unless @card.key?(:cover_url) but we would be left with
image
We can shorten that empty space, but because the checkbox only appears on hover we would have to leave an empty space above the title (case 1 kind of weird) or move the checkbox in this cases to the div where the title is but the checkbox would appear above the title (case 2)
case 1
image
case 2
image

Neither cases are good, any suggestions?

**Comment by goamaral** [comment]
Ended up extending `item_selector_input` and moving the checkbox to the right
image
image

The changes I made to `item_selector_input` should be backwards compatible

**Comment by adrianthedev** [comment]
Thanks for the PR, @goamaral, but I'm really leaning toward surfacing the workaround that you posted earlier.
I mean, it has the same result without any new code or changes for the user.

**Comment by goamaral** [comment]
The only problem with the workaround is that the card becomes unselectable because the checkbox is the cover div.
If you think this is not that relevant, we can close this. But I think the docs should be updated at least.
https://github.com/avo-hq/avodocs/pull/165

**Comment by adrianthedev** [comment]
One can use these CSS rules to hide the image, collapse the container, and still keep the checkbox in view.

```css
/* remove the `[data-resource-name="posts"]` selector to have that applied globally on every resource */
/* change `posts` to a different resource that you need */
[data-component-name="avo/index/grid_item_component"][data-resource-name="posts"] > div:first-child {
  /* we need to override the pb-3/4 class */
  padding-bottom: 2rem !important;
}

[data-component-name="avo/index/grid_item_component"][data-resource-name="posts"] > div:first-child > a {
  /* hide the link and image */
  display: none;
}
```

**Comment by adrianthedev** [comment]
Closing for now. Feel free to reopen if it's needed.

**Pull request closed without merging**
