### PR TITLE
feature: resource controls dynamic width

### LINKED ISSUE #2404: Resource controls dynamic width
### Context

Resource controls should fill up only the space it needs based on the buttons it displays.

From [here](https://discord.com/channels/740892036978442260/1039573545828753438/1199445925089788084).

### PR DESCRIPTION
**Pull request by anjoseb121**
# Description

Resource controls should use the space based on the number of actions it has. Also I've updated the padding style, now it won't show empty space when there's no action.

- Sets the padding to the first and last child for the `resource_controls_component.html.erb` component.
- Removes the `w-full` style in the `resource_controls_component.html.erb`
- Updates the fixed with of the table header to be `max-w-24`.
- Removes the `px-2` from the `table_row_component.html.erb` component, the padding is handled by the resource_controls component

Fixes #2404 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

Screenshot 2024-03-10 at 1 12 43 PM
Screenshot 2024-03-10 at 1 13 09 PM

## Manual review steps

1. Load a resource with restricted controls or without any.
1. Test left and right controls with the `config.resource_controls_placement = :left` option in the initializer

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by adrianthedev** [comment]
Thanks, @anjoseb121, for this!

I see some issues with left-side placement, and the same is true for the right side. It seems to try to take up more space than it really needs.
We'd like for the controls to only take the space they need.

I think this happens when the page is larger in width than the minimum size table.
Could you please check if that's possible?
Thank you!

CleanShot 2024-03-15 at 17 15 40@2x
CleanShot 2024-03-15 at 17 16 19@2x

**Comment by anjoseb121** [comment]
@adrianthedev thanks for the review! I've fixed it with the last commit

**Comment by adrianthedev** [comment]
Hey @anjoseb121 I pushed a few changes to account for some more scenarios.
He're how it looks on my end.
Can you please check on your end and let me know if the results are the desired ones?


CleanShot 2024-03-19 at 11 10 15@2x
CleanShot 2024-03-19 at 11 10 32@2x
CleanShot 2024-03-19 at 11 10 41@2x
CleanShot 2024-03-19 at 11 12 17@2x

CleanShot 2024-03-19 at 11 13 52@2x

**Comment by anjoseb121** [comment]
@adrianthedev Looks great! Thanks for that!

**Comment by xeron** [comment]
This looks a big ugly when `self.record_selector = false` and `config.resource_controls_placement = :left`.

Screenshot 2024-05-01 at 11 30 33 AM

**Comment by xeron** [comment]
@anjoseb121 @adrianthedev could you take a look please? ^^

**Comment by anjoseb121** [comment]
> @anjoseb121 @adrianthedev could you take a look please? ^^

@xeron sure, I can improve it!

**Comment by anjoseb121** [comment]
I just saw @adrianthedev opened [a PR](https://github.com/avo-hq/avo/pull/2740) for it, thanks for that!

**Comment by adrianthedev** [comment]
Yeah. It was a pretty wuick fix

**Pull request merged**
