### PR TITLE
Add disable_editing_values for key_value field

### PR DESCRIPTION
**Pull request by gabrielgiroe1**
# Description
Add `disable_editing_values` option for `key_value` field. Additionally, setting `disabled: true` for the `key_value` field now automatically sets `disable_editing_keys`, `disable_editing_values`, `disable_adding_rows`, and `disable_deleting_rows` to true

Fixes [#2608](https://github.com/avo-hq/avo/issues/2608)

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
  - https://github.com/avo-hq/avodocs/pull/189 
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Review by Paul-Bob — APPROVED** [review]
@gabrielgiroe1 It's looking good thank you!

Can we please add Docs and a test for this?

**Comment by gabrielgiroe1** [comment]
I add docs for this: https://github.com/avo-hq/avodocs/pull/189

**Comment by Paul-Bob** [comment]
> I add docs for this: [avo-hq/avodocs#189](https://github.com/avo-hq/avodocs/pull/189)

Looking good! Can we add a test case for the new option please? It can be done on the `key_value_field_spec.rb`

**Review by adrianthedev — APPROVED** [review]

**Comment by Paul-Bob** [comment]
@gabrielgiroe1 let's keep the previous behavior on add row button. Only disable adding row when key editing is disabled. We can have multiples keys with empty value but not vice-versa. Let's modify it on docs to, after it is ready to merge!

**Comment by adrianthedev** [comment]
This has the approved status but I see some comments. What is the status?

**Comment by Paul-Bob** [comment]
>  Let's modify it on docs to, after it is ready to merge!

This PR is good to merge, only waiting for docs update.

**Pull request merged**
