### PR TITLE
Fix links (root & custom tools)

### PR DESCRIPTION
**Pull request by nicolascochin**

### CODE REVIEW

**Comment by adrianthedev** [comment]
The changes look good. Tagging a release in an hour. 

Thank you!

**Comment by nicolascochin** [comment]
you're welcome! :-D

**Review by adrianthedev — APPROVED** [review]
Thank you for your contribution!

**Comment by adrianthedev** [comment]
Released with https://rubygems.org/gems/avo/versions/1.2.3

**Pull request merged**
