### PR TITLE
[2.x] Remove last usage of _reflections in favor of reflect_on_association.

### PR DESCRIPTION
**Pull request by simi**
- better compatible with newer Rails, since it casts to needed type on its own

successor to https://github.com/avo-hq/avo/pull/2927

I'm trying to setup Rails 7.2 for Avo 2.x CI at https://github.com/avo-hq/avo/pull/3204 as well, but it will probably need more time.

### CODE REVIEW

**Comment by simi** [comment]
I'm not 100% sure the CI failure is related to the change, I have seen same problem in other PR without this change also. :thinking:

**Comment by Paul-Bob** [comment]
Thanks for looking into this.

> I'm not 100% sure the CI failure is related to the change, I have seen same problem in other PR without this change also. 🤔

I'll have a look.

Is this still a draft?

**Comment by simi** [comment]
@Paul-Bob it is draft, since I wasn't able to get passing CI. Code-wise looks ok to me.

**Review by Paul-Bob — APPROVED** [review]
Thanks for your work on this, @simi!

I've pushed some commits to fill in the missing pieces. It's all set now, and we'll release it next week.

**Pull request merged**
