### PR TITLE
feature: Controller hooks

### LINKED ISSUE #986: [Feature] Provide hooks in controller actions
### Feature
Provide hooks on `create` or `update` after save to perform some actions. Here's what I'm trying to achieve:
```ruby
class Avo::EmailsController < Avo::ResourcesController
  def create
    super
    # This is not being called
    @model.send_as_reply
  end
end
```
Here's how it could work:
```ruby
class Avo::EmailsController < Avo::ResourcesController
  def create
    super do |resource|
      resource.send_as_reply
    end
  end
end
```

### Current workarounds
Right now, we can hook onto these actions through ActiveRecord callbacks, but it's not always convenient.

### Additional context
A simple and good implementation is the pattern used in the `devise` controllers, where the resource is being `yield` if a block is passed : https://github.com/heartcombo/devise/blob/f8d1ea90bc328012f178b8a6616a89b73f2546a4/app/controllers/devise/registrations_controller.rb#L20

### PR DESCRIPTION
**Pull request by bear-in-mind**
# Description
Provide controller hooks on `create`, `update` and `destroy` actions, to be able to easily perform some action on the resources after successful save/destroy like so:
```ruby
class Avo::UsersController < Avo::ResourcesController
  def create
    super do |record|
      record.notify("User created")
    end
  end

  def update
    super do |record|
      record.notify("User updated")
    end
  end

  def destroy
    super do
      puts "User destroyed"
    end
  end
end
```

Fixes #986 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Manual review steps
I added `create`, `update` and `destroy` methods in the `Avo::UsersController` in the dummy app. I performed some action on the yielded resource and ensured the code was executed properly.

### CODE REVIEW

**Comment by adrianthedev** [comment]
This is an interesting take on the matter (having a block to do things in).

Let me test it out for a few days please and get back to you.

**Comment by adrianthedev** [comment]
Hey man, look what an interesting idea here https://github.com/avo-hq/avo/issues/1008. So cool to have this comment so close to your proposal.

Let me think a bit more about what else we could add to make this a more complete feature and tackle it in the next release. WDYT?

**Comment by adrianthedev** [comment]
Closed by mistake 🤦‍♂️

**Comment by bear-in-mind** [comment]
Sure thing !

**Comment by dhnaranjo** [comment]
It seems like the behavior added here can be implemented with something like:

```
class Avo::UsersController < Avo::ResourcesController
  after_action -> { @model.notify("User created" }, only: :create
  after_action -> { @model.notify("User updated" }, only: :update
  after_action -> { puts "User destroyed }, only: :destroy
end
```

Maybe just some clearer documentation around how Avo controllers work so folks know they can access the model n instance resources directly??

**Comment by bear-in-mind** [comment]
Well no, the whole point is to only trigger action upon success of the request. With the implementation you propose, callbacks would be triggered even in case of failure

**Comment by dhnaranjo** [comment]
Aright, I missed that, but I think the API proposed might not be sufficiently expressive, or I wouldn't have. Maybe an `after_success_action`, which suggests an `after_failure_action` as well. It doesn't need to be in this controller action callback style, but having the action yield to a block doesn't really communicate WHEN it will yield. It'd be completely valid for it to yield on failure, or in all cases, nah mean?

**Comment by bear-in-mind** [comment]
That's very true ! I'm used to using it this way with `devise`, but I agree that it doesn't convey much meaning as to when it occurs. @adrianthedev what do you think ? Would you prefer it refactored as a more meaningful callback ?

**Comment by adrianthedev** [comment]
Thank you for brainstorming this here in public! I appreciate your support!

The way I approached most features in Avo is with multiple iterations. It seems to me to be the gentlest way of building advanced features. It's better than building the whole thing and finding out that the users might not need it or might use it differently.

So there are a few things that I see need achieving here and in #1008 (pls let me know if I missed any):

1. Customize the message after save/create/update/delete
2. Customize the path where the user is redirected after
3. Add hooks to run arbitrary code within those methods. 

Regarding number 3

1. Should the hooks receive data like the `@model`/`@resource`/`params`? My thoughts are yes. You need the context to do the action. You will have access to them if they are regular methods inside the controller.
2. Should the hooks be allowed to change that data? This is tricky, but probably yes. If they are methods inside the controller, they will be able to do that.
3. Should the hooks be before and/or after the destructive action (save/create/update/delete) happened? I'd say before and after. This will bring overhead for us on maintenance and some overhead for support (will always have to ask if those methods are overwritten, etc.), but that will bring on a lot of flexibility for Avo developers.

So I'd use the following approach:

- [ ] Create a PR for the first issue (Customize the message) similar to the devise approach.
- [ ] Create a PR for the second issue (Customize the path) similar to the devise approach. Must be careful with the [current way](https://docs.avohq.io/2.0/resources.html#customize-what-happens-after-record-is-created-edited) of doing things.
- [ ] Create a PR for the third issue after we answer those questions.

**Comment by adrianthedev** [comment]
I talked with @Paul-Bob, and we're going to prioritize this feature like so:

- We're going to implement items 1. and 2. similar to how devise implemented their callbacks (overridable methods)
- We're going to add a response interceptor so the user can respond in their own way. Example below.
- We'll document how you can already run before & after hooks with Rails' built-ins (`before_action`, `after_action`).

```ruby
      if before_response.presenet?

      else
        respond_to do |format|
          if saved
            format.html { redirect_to after_create_path, notice: "#{@resource.name} #{t("avo.was_successfully_created")}." }
          else
            flash.now[:error] = t "avo.you_missed_something_check_form"
            format.html { render :new, status: :unprocessable_entity }
          end
        end
      end
```

**Comment by adrianthedev** [comment]
Closing this in favor of https://github.com/avo-hq/avo/pull/1139

Thank you for spearheading this initiative!

**Comment by bear-in-mind** [comment]
This is great, thank you guys !

**Pull request closed without merging**
