### PR TITLE
feat: add arabic translations

### PR DESCRIPTION
**Pull request by tarekkhaled**

### CODE REVIEW

**Comment by adrianthedev** [comment]
Thank you @tarekkhaled.
Have you experimented with RTL as well? I know there have been a few people asking for that.

**Comment by tarekkhaled** [comment]
Thank you for your response. I have experimented with some RTL keys and found that they did not render correctly. Therefore, I would like to create another PR to fix this issue and add full support for RTL languages. Let me know if you have any specific requirements or suggestions for supporting RTL in your gem. 😅

**Comment by adrianthedev** [comment]
I don't have any particular requests, but just that I'd like it to look as good as LTR.
Also, I'd like to support the "Rails way" or the community way of doing things. 
I don't if RTL should come automatically when you switch to a "RTL-language", or if that should be done manually... I just don't know how others do it, so I'm going to go with your best judgment.

If you need help with styling or navigating the codebase, please shoot me a message.

And thank you for working on this!

**Comment by tarekkhaled** [comment]
from my experiments it didn't happened automatically we will need to do it manually so i will be happy to work on this in my next PR. i will reach to you if i need something thank you !

**Pull request merged**
