### PR TITLE
Replace SimpleMDE with EasyMDE

### PR DESCRIPTION
**Pull request by fastjames**
# Description
SimpleMDE has been abandoned for >6 years and is the subject of an npm security advisory. Replace the outdated library with a EasyMDE, which is a maintained fork of SimpleMDE.

Added dependencies:
* EasyMDE (https://github.com/Ionaru/easy-markdown-editor)

Removed dependencies:
* SimpleMDE (https://github.com/sparksuite/simplemde-markdown-editor/issues/829)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by adrianthedev** [comment]
Is this ready to get merged @fastjames, or do you plan on adding more things?

**Comment by fastjames** [comment]
> Is this ready to get merged @fastjames, or do you plan on adding more things?

I started this because I saw it in the `yarn audit` output, but I have not tested it very much so that's why it is still in draft.

**Comment by fastjames** [comment]
@adrianthedev I tried this locally and it rendered the in-place editor on the resource create/edit page and on the resource show page as expected.

**Comment by fastjames** [comment]
I have opened https://github.com/avo-hq/avodocs/pull/54 to update the docs for this PR.

**Comment by adrianthedev** [comment]
Thank you @fastjames!

**Pull request merged**
