### PR TITLE
add visible option for tabs

### PR DESCRIPTION
**Pull request by icaroryan**
# Description

This PR adds a `visible` option to tabs, which should hide all the contained tabs and their fields.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

https://github.com/user-attachments/assets/f4ec6cfa-e2d3-401b-a050-1c91d8767107

## Manual review steps

1. Add `visible: -> { false }` to a `tabs`
2. Make sure it hides all the tabs inside of it and their fields
3. Move set it back to true and they should reappear
5. Ensure it doesn't hide anything when visible isn't set

### CODE REVIEW

**Comment by icaroryan** [comment]
@Paul-Bob @adrianthedev when are you guys doing the next release? I just want to have an idea so that I can get this ticket done in time to be released with the others

**Comment by Paul-Bob** [comment]
I already started the release process, there is no hurry, this can be included in the next minor release. Let me know if is this blocking somehow any project you're working on.

**Comment by icaroryan** [comment]
Hey @Paul-Bob, this PR is ready for review. I'll be adding the documentation for this and the others as soon as I can
Thank you!!

**Review by Paul-Bob — APPROVED** [review]
It's looking good. Thank you for the contribution @icaroryan!

**Comment by Paul-Bob** [comment]
Issue for docs https://github.com/avo-hq/docs.avohq.io/issues/265

**Pull request merged**
