### PR TITLE
feature: find record method

### PR DESCRIPTION
**Pull request by adrianthedev**
# Description

Fixes https://github.com/avo-hq/avo/issues/1165

[Prerelease](https://rubygems.org/gems/avo/versions/2.25.1.pre.1.pr1579)
[Docs](https://docs.avohq.io/2.0/customization.html#custom-find-method-for-show-and-edit-pages)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Go to `/admin/people`
2. select a person
3. observe the param is the person name, not the `id`

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by adrianthedev** [comment]
I'm moving the conversation here @segiddins.
Can you try version [2.25.1.pre.1.pr1579](https://rubygems.org/gems/avo/versions/2.25.1.pre.1.pr1579) and see if that works for you?

To set a custom find method add the `find_record_method` class attribute to your resource.

```ruby
self.find_record_method = ->(model_class:, id:) {
  model_class.find_by something: id
}
```

**Comment by segiddins** [comment]
I'll give it a try! One question: should it be `find_by!` instead for consistency with the prior behavior of using `find`?

**Comment by adrianthedev** [comment]
Hmmm. I think so, yes.

**Comment by segiddins** [comment]
It works, thanks so much @adrianthedev!

**Comment by adrianthedev** [comment]
Nice! You can use that version for now. I'll add a few tests and release a new one soon.

**Pull request merged**
