### PR TITLE
fix: use base class for link helpers with STI models

### PR DESCRIPTION
**Pull request by adrianthedev**
Fixes https://github.com/avo-hq/avo/issues/559 and https://github.com/avo-hq/avo/discussions/549

### CODE REVIEW

**Comment by adrianthedev** [comment]
@rctneil can you try [1.18.2.pre.0](https://rubygems.org/gems/avo/versions/1.18.2.pre.0) and test it thoroughly?

In your testing, you should remove the `SpouseResource` and `SpouseController`. If all is ok, I'll merge it and release it.

**Comment by rctneil** [comment]
@adrianthedev Hi Adrian,

Many thanks for putting this pre-release out.   I've done some testing in my app today and it does appear to be working so far.  I will raise an issue if I hit any issues regarding that aspect.

One quick question, is there a way to get a text field to link to another record?  Eg, a text field on a show view to link to a corresponding show view?

**Comment by adrianthedev** [comment]
Awesome!

I just pushed [a PR](https://github.com/avo-hq/avo/pull/561) allowing `as_html` to text fields.

**Comment by adrianthedev** [comment]
Actually a better option for that is the `format_using` [option](https://docs.avohq.io/1.0/field-options.html#fields-formatter) setting. You should try that one instead.

**Pull request merged**
