### PR TITLE
Enable configuring search_count per resource

### LINKED ISSUE #2901: Configure `search_count` per resource
### Context

As a follow up for https://github.com/avo-hq/avo/issues/2885 lets also enable resource level configuration for the search query limit.

#### Approach

1. Fetch the `results_count` from the search options like we do with the query [here](https://github.com/avo-hq/avo/blob/main/lib/avo/base_resource.rb#L213)
2. Execute it using `Avo::ExecutionContext` like we do with the `search_query` [here](https://github.com/avo-hq/avo/blob/main/app/controllers/avo/search_controller.rb#L44)
3. Make sure that `results_count` can be both, an integer or a Proc
4. Make sure that resource level `results_count` takes precedence over the global configuration `Avo.configuration.search_results_count`
5. Add docs somewhere around [here](https://github.com/avo-hq/docs.avohq.io/blob/main/docs/3.0/search.md#L305) 

Final DSL should look like:
```ruby
class Avo::Resources::User < Avo::BaseResource
  self.search = {
    query: -> { query.ransack(name_eq: params[:q]).result(distinct: false) },
    results_count: -> { user.admin ? 30 : 10 }
  }
end
```

### PR DESCRIPTION
**Pull request by binarygit**
# Description
This PR allows setting the search count on a per resource basis. It makes sure that the resource specific count takes precedence over the global configuration.

Fixes #2901
# Checklist:
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. In the dummy app, inside resources/user.rb, I set count to 5.
2. Navigated to /admin/resources/users.
3. Typed 'a'. Verified that only 5 search results were displayed out of 39.

---

1. In the dummy app, inside resources/user.rb, I set count to -> { 3 }.
2. Navigated to /admin/resources/users.
3. Typed 'a'. Verified that only 3 search results were displayed out of 39.

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by binarygit** [comment]
@Paul-Bob I think this should be tested. However I'm not sure where the search related tests are written. If you could tell me, then I'd be happy to write tests for this.

**Comment by binarygit** [comment]
Not sure why CI's failing :shrug: . I checked the failing specs locally and they pass
passing

**Comment by Paul-Bob** [comment]
It's looking great! Thanks @binarygit 

`spec/features/avo/search_has_many_scope_spec.rb` is an example of a search controller test.

We have some helpers for system tests if you want to go that way. 

- [`write_in_search`](https://github.com/avo-hq/avo/blob/feature/hide_empty_menu_groups_and_sections/lib/avo/test_helpers.rb#L118)
- [`select_first_result_on_search`](https://github.com/avo-hq/avo/blob/feature/hide_empty_menu_groups_and_sections/lib/avo/test_helpers.rb#L129)
- [`click_resource_search_input`](https://github.com/avo-hq/avo/blob/feature/hide_empty_menu_groups_and_sections/lib/avo/test_helpers.rb#L101)

Don't worry about the CI tests I'll have a look, it seems unrelated.

**Comment by adrianthedev** [comment]
hey @binarygit. 
I'd like to write something to you.
How can I reach you? can you share your email, or are you on our [discord](https://avo.cool/chat)?

**Comment by binarygit** [comment]
Here’s my email @adrianthedev : avii@hey.com

**Comment by binarygit** [comment]
@Paul-Bob I added the tests. Let me know what you think :pray:

**Review by Paul-Bob — APPROVED** [review]

**Comment by Paul-Bob** [comment]
Thank you for the contribution @binarygit !

**Pull request merged**
