### PR TITLE
feature: add optional collapsible option

### LINKED ISSUE #1551: Alias `collapsable` as `collapsible`
### Feature

```ruby
section "Resources", icon: "resources", collapsable: true do
  resource :course
end
```
Add an alias for `collapsable` as `collapsible` on menu editor.

Reason: 

> "Collapsable" is an adjective for something that can collapse, and "collapsible" is an adjective for something capable of collapsing. Both words have the same definitions. Although the most common writing is "collapsible."

Source: https://thecontentauthority.com/blog/collapsable-vs-collapsible

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #1551

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Paul-Bob** [comment]
@adrianthedev is there a way to use an alias for dry-initializer options? I did not found any that's why i came up with this workaround.

**Comment by adrianthedev** [comment]
How about we leave it like this for Avo 2 and rename the option to `collapsible` in Avo 3 (with upgrade guide). This way we don't confuse people with two names for the same options here and we fix it in the next version.
WDYT?

**Comment by Paul-Bob** [comment]
Not sure if renaming it add any value, both words ("collapsible" and "collapsable") apply on this context. They end up meaning the same thing. Or do you think "collapsible" apply better on the menu context? Anyway, fell free to close this one, we can discuss and implement it if needed on Avo 3

**Comment by adrianthedev** [comment]
Let's leave it like it is now. We'll see next time when this pops up

**Pull request closed without merging**
