### PR TITLE
Extract pundit to client

### PR DESCRIPTION
**Pull request by dhnaranjo**
# Description
Auth changes are stressful so let's do it in pieces. The goal of this PR is to pull all direct interaction with Pundit into a single client class AND simplify the AuthorizationService.

I believe that we should only need two public methods on the auth service and clients, `authorize` and `apply_policy`, with errything else being kind of implementation details that are obscuring what you're really trying to get done.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

This is a WIP, I'm leaving comments about other things I'm thinking on to discuss. I'll squash the lil commits when it's time but for now it helps with following what I'm up to.

### CODE REVIEW

**Comment by dhnaranjo** [comment]
I'm thinking that the behavior provided by `AuthorizationService#has_method?`, which wraps a few calls to `authorize_action`, and the policy existence conditional and catch for missing policy in `AuthorizationService.authorize` are both dancing around an option for `.authorize` that's like... `pass_if_policy_missing`. That'd look something like:

```
def authorize(user, record, action, policy_class: nil, **args)
  client.authorize(user, record, action, policy_class:)
rescue NoPolicyError => error
  if args[:pass_if_policy_missing] == true
    true
  elsif Avo.configuration.raise_error_on_missing_policy
    raise error
  else
    false
  end
end
```

**Comment by adrianthedev** [comment]
Thanks for championing this task @dhnaranjo! I'm a bit unavailable today and tomorrow, but it's on my to-do list.
So, if I don't get the time today or tomorrow to review and respond, I'm on it on Wednesday.

GG for the approach 💪

**Comment by thiagovsk** [comment]
@dhnaranjo I really like this effort, I want to use cancancan instead of pundit, I think that with your PR I can create another authorizatio_client/can_can_can supporting it, what do you think about it?

**Comment by dhnaranjo** [comment]
@thiagovsk thats totally the plan. Folks can contribute clients or you'll be able to supply your own that's in your codebase.

**Comment by thiagovsk** [comment]
> @thiagovsk thats totally the plan. Folks can contribute clients or you'll be able to supply your own that's in your codebase.

@dhnaranjo amazing, let me know if you need any help, good job!

**Comment by adrianthedev** [comment]
Hey @dhnaranjo. I wanted to give you a heads-up that I'm still reviewing this PR. I started to review it about three times already, and I want to make sure it doesn't break any existing apps.

I found a bug, but it's not because of this PR.

Again, thanks for taking the time to work on this. From my initial review, this looks very promising. I noticed you put a lot of effort into this. Thank you!

I want to have this merged before the next release (next Tuesday).

**Comment by adrianthedev** [comment]
Ok. the tests are passing. 

https://media.giphy.com/media/3o6vXVzKWtkOIpyNMs/giphy.gif

@dhnaranjo do you want to try and create an action_policy client on your local machine to make sure we have everything we need?

@thiagovsk would you like to try and create a `can_can_can` client on your machine and see if you have everything you need?

You can set the client in the initializer like so:

```ruby
# config/initializers/avo.rb
config.authorization_client = "Avo::Services::AuthorizationClients::ActionPolicyClient"
```

**Comment by adrianthedev** [comment]
We can improve the configuration bit like @dhnaranjo suggested [here](https://github.com/avo-hq/avo/pull/1142/files#diff-57b671e89daceaec663c57f6ebdbbee4b13b628270e308fc6eb77366e0da83a5R10).

**Comment by adrianthedev** [comment]
Merging this as is and we'll make updates on the go.

**Comment by adrianthedev** [comment]
@dhnaranjo [there is someone else](https://discord.com/channels/740892036978442260/740893011994738751/1072154792618643577) that would like to use the action_policy authorization client.

Would you share the snippet to that client you are using so others can use it too?

**Comment by olivierbuffon** [comment]
@dhnaranjo +1 I'd alos be interested to see your implementation of the action_policy client. 🙏🏻

**Comment by dhnaranjo** [comment]
There's an issue for its inclusion here: https://github.com/avo-hq/avo/issues/1922. The OP pretty much implemented it the same way I had. @adrianthedev pardon me for missing that request.

**Pull request merged**
