### PR TITLE
Fix init script

### PR DESCRIPTION
**Pull request by marcelobarreto**
Hi guys :wave: 

This is my first PR for avo!

While trying to setup everything, I found a problem while trying to run the `bin/init` that was solved with that tiny change.

### CODE REVIEW

**Comment by adrianthedev** [comment]
I'm curious what were the issues with `downcase`? It seems to work on my end when I input `y`.

**Comment by marcelobarreto** [comment]
When I choose `N` is converting to `n`

**Comment by adrianthedev** [comment]
Well, it doesn't really do anything capitalized or not 🙃
This script needs a bit more love but decided to do it at a later time.

**Comment by marcelobarreto** [comment]
haha, let me know if you need any help with this script, I can help :muscle:

**Pull request merged**
