### PR TITLE
feature: dashboards

### PR DESCRIPTION
**Pull request by adrianthedev**

### CODE REVIEW

**Comment by rickychilcott** [comment]
I'm appreciating where this work is headed, but I'm a little confused. The docs say that [dashboards needs 1.21+](https://docs.avohq.io/1.0/dashboards.html), but when I look at this PR, it's not merged and I'm not seeing a `Dashboards` class in `main` or a gem release.

Am I missing something?

**Comment by adrianthedev** [comment]
Hey @rickychilcott. My mistake there. I apologize. 
I thought I would push it out sooner than this, but the plans have changed a bit.

I'm working on releasing Avo 2.0 at the moment. It will be released in two weeks at the latest. Dashboards will be a feature of 2.0.
I updated the docs to reflect that.

Is Dashboards a feature you're looking forward to having in Avo?

**Comment by adrianthedev** [comment]
That's not a bad idea @rickychilcott. I'll make sure that's supported very soon after the dashboards launch (which I hope to deliver next week).

https://github.com/avo-hq/avo/issues/721

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/pull/727

**Comment by adrianthedev** [comment]
Hey @rickychilcott,

2.0 is out with the Dashboards feature.
`iframe`s are supported from day 1 💪

https://docs.avohq.io/2.0/dashboards.html#cards

**Comment by rickychilcott** [comment]
Excited to check it out in the next few weeks. Thank you!

**Pull request closed without merging**
