### PR TITLE
feature: profile and cover photos

### PR DESCRIPTION
**Pull request by adrianthedev**
# Description

Adds a cover and profile photo to the show view of the record.

CleanShot 2024-04-25 at 11 46 47@2x

# Todo:

- [ ] Add cover images to the index/edit page
- [ ] add support for plain paths (interpolated with the record data) (Paul's suggestion)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Review by Paul-Bob — CHANGES_REQUESTED** [review]
Looking great!

I have one concern about the way to declare the cover/photo components. IMO it should not rely on existing fields, and pass the photo URL directly on the API like grid view cover.

Pros: 
- Any image can be used even an external URL
- Custom path helpers can be used to get the image URL
- No need of field declaration if user don't want to have that fields.

```ruby
self.cover_photo = -> do
  {
    # size: :sm,
    source: main_app.url_for(record.cover_photo.url)
  }
end
```

**Comment by adrianthedev** [comment]
yup! makes sense!
Thanks for the review!

**Comment by adrianthedev** [comment]
Let's look into memoization of these obejcts (`profile_photo` & `cover_photo`) from the concern.

**Comment by adrianthedev** [comment]
Implements RSpec tests for Avo's event page cover and profile photos components, ensuring proper visibility under various conditions.

- **Adds component tests** for both `Avo::CoverPhotoComponent` and `Avo::ProfilePhotoComponent` to verify rendering logic based on the presence and visibility of photos. These tests cover scenarios where photos are present, absent, not visible in the current view, and dynamically sourced.
- **Updates feature tests** in `spec/features/avo/cover_profile_photos_spec.rb` to include scenarios for an event page without cover and profile photos, with only a cover photo, with only a profile photo, and with both photos. This ensures the application behaves as expected under each condition.


---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/avo-hq/avo/pull/2722?shareId=76ee8294-b3dd-4b08-b5a6-3fb721ad01af).

**Review by Paul-Bob — APPROVED** [review]

**Pull request merged**
