### PR TITLE
Fix: Side menu always displays

### LINKED ISSUE #3059: Side menu always displays
### Describe the bug
On upgrading from Avo 3.10.7 to 3.10.8 or 3.10.9, the side menu on mobile view is always displaying when either a resources menu item or a record link is clicked. 

### Steps to Reproduce
1. Switch to a mobile view
2. Click on a resources menu item

### Expected behavior & Actual behavior
For Avo 3.10.7, when a resources menu or link is clicked on the mobile view, no side menu appears when the new page has been loaded. For Avo 3.10.8 and 3.10.9, the side menu is always displayed.

### System configuration
**Avo version**:
3.10.9

**Rails version**:
7.1.3.4

**Ruby version**:
3.3.4

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://github.com/user-attachments/assets/7ad381b2-0e6b-4fb8-9e60-4f5380284fa4

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

### PR DESCRIPTION
**Pull request by binarygit**
# Description

This PR ensures that the correct cookie is set after a user toggles the sidebar

Fixes #3059

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

https://github.com/user-attachments/assets/a6498a28-5f49-496e-9be6-edb72ba66cfd

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Review by Paul-Bob — APPROVED** [review]

**Review by adrianthedev — CHANGES_REQUESTED** [review]
Can we make it so on initial load (so no cookie was set) it's not visible?
Try it in incognito to see what I mean.

**Review by adrianthedev — CHANGES_REQUESTED** [review]
The previous issue is fixed, but it does not behave correctly.
It's still open on subsequent navigation.

https://github.com/user-attachments/assets/934e2ab0-99f7-4e08-910e-48bcc06705c9

**Comment by binarygit** [comment]
@adrianthedev 
Could you look at my latest commit?

I preserved the old behaviour:

https://github.com/user-attachments/assets/27454889-d560-4aff-a231-a6523ecb9ee8

However, when the page loads and the user hasn't toggled the sidebar yet, the sidebar "pops" open rather than "sliding out" because the js executes a little later than the css and the user can't see the transition. After this subsequent toggles do show the transition.

I'm not sure how to keep the sidebar hidden on mobile at first render and then also have it show the transition.

**Comment by Paul-Bob** [comment]
The JS removes then adds `sidebar-open` very quickly and the browser doesn't have time to apply the transitions.

Let's force a reflow on it.

**Pull request merged**
