### PR TITLE
feature: Select all on controller

### PR DESCRIPTION
**Pull request by chrismdp**
Simple Stimulus controller which uses JS to click all select buttons on the page at once, and additionally ensures the status of the checkbox is consistent with the row checkboxes.

The implementation isn't efficient and might get slow with very large pages, but felt like the simplest option for now that could work.

First proper PR - feedback very welcome! Happy to work on improving this as needed.

Closes #452.

### CODE REVIEW

**Comment by adrianthedev** [comment]
👀 Checking it right now.

**Comment by chrismdp** [comment]
The tests seemed to fail for unrelated reasons 🤔

**Comment by adrianthedev** [comment]
Yup. Totally unrelated. There's an issue with the `ViewComponent` library.

**Comment by adrianthedev** [comment]
Released in `1.11.5`

**Pull request merged**
