### PR TITLE
Render action controls without adding to actions method

### LINKED ISSUE #2917: Decouple actions in the custom controls from the actions in the `def actions` method
### Context

Right now there's a limitation of not being able to use an action in the custom controls area (show, index, edit, row) unless it's added first in the `def actions` method of the resource.

This can lead to [issues](https://github.com/avo-hq/avo/issues/2908) with displaying the actions in different contexts and doing weird gymnastics around it to support advanced use-cases.

### Proposal

Let's decouple those two and fix those issues once and for all.

### PR DESCRIPTION
**Pull request by binarygit**
# Description

Fixes #2917 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by binarygit** [comment]
@adrianthedev The tests pass for me locally. But I can't re trigger the job!

**Comment by adrianthedev** [comment]
Let's add some tests to this as well

**Review by Paul-Bob — APPROVED** [review]
This is one of those issues that requires a whole adventure to find the fix. :D

I tested it locally, and it works as expected.

Thanks for digging into this @binarygit

**Review by adrianthedev — CHANGES_REQUESTED** [review]
Great job!
Let's add some tests to future-proof this feature.

**Pull request merged**
