### PR TITLE
Feature: hide/show content for Trix fields

### PR DESCRIPTION
**Pull request by zhephyn**
# Description
On show pages, content is hidden by default. A "Show Content" link is displayed too which when toggled "shows" said content. 
For this PR, a "Hide content" link is added, allowing us to toggle between showing the content and hiding it as desired, by clicking either the "Show content" link or the "Hide content" link. 

Fixes https://github.com/avo-hq/avo/issues/1871

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording
With this change, the updated UI of the show page is like below
image
image

### CODE REVIEW

**Comment by Paul-Bob** [comment]
Hi @zhephyn thanks for all your effort on this contribution.

Last week, we received a PR related to this same feature, and it turns out we had two issues tracking it.

 I'll close this one in favor of https://github.com/avo-hq/avo/pull/3359

Thank you!

**Comment by zhephyn** [comment]
Hey @Paul-Bob.Thanks for the kind words. Could the issue #3359 be assigned to me and I work through it? Also, I noticed so many issues with a "Good first issue" label attached to them. I could submit PR's after working through them so that I don't have to trouble you with assigning each of them to me individually. Is that fine by you? Thanks in advance.
PS: I'd like to mention that regardless of the fact that my PR wasn't merged, just working through the entire process related to the feature was a good learning experience.

**Comment by Paul-Bob** [comment]
> Could the issue https://github.com/avo-hq/avo/pull/3359 be assigned to me and I work through it?

[Nevelito](https://github.com/Nevelito) is already working on that one, we had these two issues that were tracking the same feature, that's on us.

>Also, I noticed many issues with a "Good first issue" label attached to them. I could submit PR's after working through them so that I don't have to trouble you with assigning each of them to me individually. 

Is important to be assigned before working on it, otherwise, we could receive multiple contributions on the same issue. Feel free to tag me or Adrian on the issue and include any questions. We’ll assign it to you and respond as soon as we can.

> PS: I'd like to mention that regardless of the fact that my PR wasn't merged, just working through the entire process related to the feature was a good learning experience.

That's awesome! Let me know if you'd like to try another issue. I'd be happy to guide you through it.

**Comment by zhephyn** [comment]
Yeah, I'd love to try out another issue amongst those that are unassigned at the moment. Please just link the issue number and I'll start working on it.

**Comment by Paul-Bob** [comment]
> Yeah, I'd love to try out another issue amongst those that are unassigned at the moment. 

Cool!

> Please just link the issue number and I'll start working on it.

I wasn't thinking of any particular issue, you can pick one labeled as  "Good first issue" and tag me there

**Pull request closed without merging**
