### PR TITLE
security: don't expose rails version

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Don't expose rails version

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by adrianthedev — CHANGES_REQUESTED** [review]
Wait pleas

**Comment by Paul-Bob** [comment]
Original request: https://discord.com/channels/740892036978442260/1039573545828753438/1285495485057990740

@yuki-yogi After discussing with @adrianthedev the exposed rails version can be helpful in some scenarios. Not merging for now

**Comment by yuki-yogi** [comment]
@Paul-Bob 
Thank you for the discussion. Understood.
My product uses avo3 in a freemium-like model, so it might be a special case.

Thank you for always considering and replying quickly 👍

**Comment by adrianthedev** [comment]
Closing in favor of https://github.com/avo-hq/avo/pull/3287

**Pull request closed without merging**
