### PR TITLE
feature: add visible option to panels

### PR DESCRIPTION
**Pull request by icaroryan**
# Description
This PR adds a `visible` option to Panels, which should hide all the contained fields as well as the panel.

This new option shouldn't affect `main_panel` only `panel`

Fixes [#https://github.com/avo-hq/avo/issues/2971](https://github.com/avo-hq/avo/issues/2971)

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

https://github.com/user-attachments/assets/0bfa2d76-6ff3-4f31-80dd-3ab6453ca63c

## Manual review steps

1. Add `visible: -> { false }` to a panel
2. Make sure it hides all the panel header and all fields contained
3. Move set it back to true and they should reappear
4. Ensure it doesn't work when changing the visibility of `main_panel`
5. Ensure it doesn't hide anything when visible isn't set

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by icaroryan** [comment]
Ayy, my first collaboration!
I was wondering where I'd add automated tests for this feature. I couldn't find the proper file to write them

**Comment by Paul-Bob** [comment]
Hello @icaroryan you made it! 

Thanks for the contribution, it's looking good.

Most Avo test files are under the `spec/features/avo/**` and `spec/system/avo/**` paths.

We have [this test](https://github.com/avo-hq/avo/blob/469636c685bc55e44e7cede6061b637e2e174d0b/spec/features/avo/tabs_panels_and_sidebar_visibility_spec.rb) that already checks the visibility of tabs, panels, and the sidebar. The purpose of this test is to ensure that none of these elements are rendered if their respective fields are hidden. You can add a test case for panel visibility block inside it.

**Comment by icaroryan** [comment]
Thank you @Paul-Bob! Just pushed the new tests

**Comment by icaroryan** [comment]
With that being said, I think it’s worth having the same option for tab. If you give me the go-ahead, I can push a PR for it. It would be basically the same thing we did with panels.

**Comment by Paul-Bob** [comment]
> Thank you @Paul-Bob! Just pushed the new tests. I tried to follow the same structure of the existing ones

Looking great, Thanks!

DOCS PR (just to remain linked): https://github.com/avo-hq/docs.avohq.io/pull/248

> With that being said, I think it’s worth having the same option for tab. If you give me the go-ahead, I can push a PR for it. It would be basically the same thing we did with panels.

I would be happy to merge it, thanks for the initiative, we appreciate it!

**Pull request merged**
