### PR TITLE
Backport #2431 to 2.x branch

### PR DESCRIPTION
**Pull request by iainbeeston**
# Description

In #2431 I fixed a bug where (at some point) the filename on a file field was hidden. The fix was only applied to the 3.x branch but I'd like to use it in 2.x as well.

Fixes # (issue)

The filename on a file input is hidden.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Find a file input on an avo 2.x app
2. Upload a file
3. Confirm that the filename is visible (it should be with this patch, but wasn't before)

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by adrianthedev** [comment]
@Paul-Bob could you please lend a hadn here. I don't know exactly why the tests try to call an external path.
Probably related to chrome webdrivers?

**Comment by Paul-Bob** [comment]
This PR is inserting an issue that happens on `stacked` fields please check https://github.com/avo-hq/avo/issues/2473

**Comment by Paul-Bob** [comment]
@iainbeeston I guess you don't use stacked on file fields right? Any clue about the issue introduced on stacked fields by this PR?

**Comment by iainbeeston** [comment]
@Paul-Bob sorry, no - I didn’t even know about stacked fields until you mentioned that issue!

**Pull request merged**
