### PR TITLE
add date-time filter

### PR DESCRIPTION
**Pull request by OlexYakov**
# Description
Date-time filter. Enables the user to create filters by date or date-time, on any timestamp field. Relevant feature request #1226

Fixes https://github.com/avo-hq/avo/issues/1226

# Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by OlexYakov** [comment]
Currently on vacation, I'll add tests and documentation when I come back, in a few days.

**Comment by adrianthedev** [comment]
Now worries man. Enjoy your time off! This is an amazing start!

**Comment by adrianthedev** [comment]
Also, I wonder if we could use the [native field components](https://docs.avohq.io/2.0/native-field-components.html) to render the inputs for the date filter.

**Comment by adrianthedev** [comment]
Closing for now. We'll probably land this in Avo 3

**Pull request closed without merging**
