### PR TITLE
🥑

### PR DESCRIPTION
**Pull request by joeldrapper**
# Description

Fixes missing 🥑

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps
1. Step 1 — Ran `bin/rails c`
1. Step 2 — Confirmed `🥑 == Avo`

### CODE REVIEW

**Comment by stevegeek** [comment]
LGTM. 🚢

**Review by adrianthedev — APPROVED** [review]
🥑

**Review by Paul-Bob — APPROVED** [review]
image

**Comment by adrianthedev** [comment]
Brainstormed, contributed, and merged during the 2024 Euruko in Sarajevo 🙌

**Pull request merged**
