### PR TITLE
Fix nested render table component

### PR DESCRIPTION
**Pull request by yorch**
# Description

Fixes issue when rendering the nested resources table.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

Description...

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by adrianthedev** [comment]
Not sure I understand the fix here 😅. Can you share what is broken and how this fixes it?

**Comment by adrianthedev** [comment]
@yorch is this PR still of interest? Still not sure what is it that it's fixing.

**Comment by yorch** [comment]
At least from the application I'm working on, this is needed to fix nested tables on resources.. not sure if you tested the use case, but might be good idea to try to replicate the issue in the dummy app

**Comment by adrianthedev** [comment]
Yeah, that's a good idea. Have you been able to replicate it on [avodemo](https://avodemo.herokuapp.com/)?

The user resource has a lot of has_many associations.

CleanShot 2022-04-05 at 09 36 03

**Comment by adrianthedev** [comment]
Closing this until we have a clear replicable issue. Feel free to open if this pops up again.

**Pull request closed without merging**
