### PR TITLE
fix: fields x overflow

### LINKED ISSUE #3530: UI: #show sidebar - long string overflow
### System configuration
**Avo version**: 3.15.2

**Rails version**: 8.0.0

**Ruby version**: 3.3.3

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

Image

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #3530

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

#### Before

https://github.com/user-attachments/assets/4f665ea2-682f-4a9d-8d7a-81273c0c4f19

#### After

https://github.com/user-attachments/assets/1cd32e31-8c16-4f04-82b2-1ea1ab8fb4b9

### CODE REVIEW

**Comment by adrianthedev** [comment]
let's wait a bit... 😅
I don't like it that much. I don't have other solutions either :P just saying.

**Comment by ObiWanKeoni** [comment]
> let's wait a bit... 😅 I don't like it that much. I don't have other solutions either :P just saying.

👋 Unsolicited comment:
Do any of [these](https://tailwindcss.com/docs/word-break) look any better?

**Comment by Paul-Bob** [comment]
> > let's wait a bit... 😅 I don't like it that much. I don't have other solutions either :P just saying.
> 
> 👋 Unsolicited comment: Do any of [these](https://tailwindcss.com/docs/word-break) look any better?

IMO `break-words` looks good, thanks for sharing!

**Comment by adrianthedev** [comment]
@ObiWanKeoni feel free to throw all the unsolicited advice towards us.
We'll gladly take it! 
Thanks for your stellar [PR](https://github.com/avo-hq/avo/pull/3516). We haven't forgot about it, we just need a bit more time to get into that headspace.

**Pull request closed without merging**
