### PR TITLE
fix: `break-words` on show content

### LINKED ISSUE #3530: UI: #show sidebar - long string overflow
### System configuration
**Avo version**: 3.15.2

**Rails version**: 8.0.0

**Ruby version**: 3.3.3

**License type**

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

Image

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #3530 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

### Before

image

### After

image

### CODE REVIEW

**Comment by adrianthedev** [comment]
Can you please check to see if it looks ok with the `created_at` example we had on the initial issue?

**Comment by Paul-Bob** [comment]
> Can you please check to see if it looks ok with the `created_at` example we had on the initial issue?

Where were we checking it?

**Comment by Paul-Bob** [comment]
> Can you please check to see if it looks ok with the `created_at` example we had on the initial issue?

image

**Review by adrianthedev — APPROVED** [review]

**Comment by adrianthedev** [comment]
Awsome! thanks!

**Pull request merged**
