### PR TITLE
fix: date field format in mobile browsers

### LINKED ISSUE #975: Date format is not working in mobile browsers
### Describe the bug
Display format for date fields doesn't work in mobile browsers. In web, it works fine

### Steps to Reproduce
1. Configure a resource with date field
2. Specify a custom format for date
3. Go to new/edit page in web & mobile browsers

### Expected behavior
Web & Mobile: Date should be displayed in the specified format

### Actual behavior
Web: Date is displayed in the specified format
Mobile: Date **is not** displayed in the specified format

### System configuration
**Avo version**: 2.4.1

**Rails version**: 7.0.2.3

**Ruby version**: 3.1.1

**License type** (Community or Pro): Community

**Resource Field Config**: `field :date, as: :date, required: true, picker_format: 'd F, Y', format: '%d %B, %Y', default: Date.today`
### Screenshots
**Web**
Date Field - Web
**Mobile**
Date Field - Mobile

#### Impact

 - [ ] High impact
 - [ ] Medium impact
 - [x] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] Low urgency

### PR DESCRIPTION
**Pull request by hassyyy**
# Description

Fixes #975 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Configure a resource with date field
2. Specify a custom format for date and set `disable_mobile` to `true`
3. Go to new/edit page in web & mobile browsers

**Example:**
```ruby
field :date, as: :date, required: true, picker_format: 'd F, Y', format: '%d %B, %Y', default: Date.today, disable_mobile: true
```

**Output:**
Date Field - Mobile - Fixed

### CODE REVIEW

**Comment by adrianthedev** [comment]
Thank you for the contribution!

**Comment by hassyyy** [comment]
Wow. That's super fast merge 😀

@adrianthedev Hope you will take care of updating the documentation

**Comment by hassyyy** [comment]
Hey @adrianthedev, there is a small typo in the doc. It should be `disable_mobile` instead of `disabled_mobile`. Kindly fix that

**Comment by adrianthedev** [comment]
🙌 thank you! Pushed a fix!

Me too. Looking forward to more community contributions.

**Pull request merged**
