### PR TITLE
fix: undefined tags in field when editing

### PR DESCRIPTION
**Pull request by coatezy**
# Description

This PR fixes an undefined tag issue when editing existing tags on a resource.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

**Before:**

CleanShot 2024-10-08 at 13 12 48@2x
CleanShot 2024-10-08 at 13 00 44@2x

**After:**
CleanShot 2024-10-08 at 13 13 08@2x

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Comment by Paul-Bob** [comment]
Hey @coatezy thanks for the contribution! I noticed that some tests are failing. Could you please share the tags field code from your resource and more details about how to reproduce the issue?

**Comment by coatezy** [comment]
> Hey @coatezy thanks for the contribution! I noticed that some tests are failing. Could you please share the tags field code from your resource and more details about how to reproduce the issue?

Hey, @Paul-Bob! Not problem. I'd be happy to try and understand why these are failing. The tags field is configured in the following way on the resource.

```
    field :tags, as: :tags, acts_as_taggable_on: :tags
```

**Comment by Paul-Bob** [comment]
I was able to reproduce the issue, I guess the tests are failing because tags cover several use cases and this change fixes this particular use case but maybe is breaking other use case, I'll also have a look

**Review by Paul-Bob — CHANGES_REQUESTED** [review]
I suggested some changes that might be effective.

When using `suggestions` https://docs.avohq.io/3.0/fields/tags.html#possible-values as an array of hashes the `possibleSuggestion` will respond to `label` but when used as array of values or not used at all it will NOT respond to `label`

**Review by Paul-Bob — APPROVED** [review]
Thank you for this contribution @coatezy!

Some tests were failing, so I made a change to ensure that tags function correctly in other scenarios.

**Pull request merged**
